version: "3.7"
volumes:
  database:
services:
  db:
    image: mysql:latest
    container_name: rent_easily_db
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=r3nt_3@s1ly
      - MYSQL_DATABASE=rent_easily_DB
      - MYSQL_USER=rent_easily
      - MYSQL_PASSWORD=r3nt_3@s1ly
